### ISSUE TITLE
NgCordova?

### ISSUE THREAD

**Issue by francesco-strazzullo** [save91/tesi_2016#2]
All'interno del capitolo dei Beacon parli di NgCordova. Mi sembra un po' strano visto che di Ionic si è parlato davvero poco. Le strade che vedo sono due: o non parli di ngCordova oppure ti prendi un paragrafo per parlare velocemente di come è impostata un'app Ionic e il perché della nascita del progetto ngCordova. Deve essere un piccolo paragrafo che serve solo per dare contesto: poi anche poi fare riferimento alla tesi di Marco...

**Comment by save91** [comment]
Mi sembra più saggia la prima strada

**Comment by francesco-strazzullo** [comment]
Sì devo dire che mi sembra saggio!
